simulator_name: 'zigzag_reading'

rl:
  mode: test    # Select from: train, test, debug (check_env many times for the baseline), and interact.

  train:
    total_timesteps: 6000000
    checkpoints_folder_name: 'checkpoints_0203_6M_50'
    num_workers: 12   # As long as it is smaller than the laptop's number of processes: 16.
    num_steps: 3600
    algorithm: 'PPO'
    policy_type: 'MultiInputPolicy'
    policy_kwargs:
      activation_fn: 'torch.nn.LeakyReLU'
      net_arch: [256, 256]
      log_std_init: 0.0
      features_extractor_class: 'RLPipeline.CustomCNN'
      features_extractor_kwargs: dict(features_dim=128)
      normalize_images: False
    batch_size: 300   # We recommend using a `batch_size` that is a factor of `n_steps * n_envs`.
    target_kl: 1.0
    device: 'cuda'
    save_freq: 50000  # Save a checkpoint every 0.5 million steps.

  # Note, before starting the pipeline, make sure the testing and training environment settings are consistent.
  test:
    num_episodes: 1
    loaded_model_name: 'rl_model_2749560_steps'

mj_env:
  filename: 'zigzag-reading-v0131.xml'
  render:
    is_window_visible: 0        # Set to 0, use off-screen buffer provided by OpenGL, enable the headless rendering, and disable all the GUI interactions.
                                # Set to 1, use the default window buffer provided by the operating system, enable the GUI interactions.
    width: 80                   # Default: 80
    height: 80                  # Default: 80
    rgb: yes                    # Choose from yes or no.
    depth: no                  # Choose from yes or no.

task:
