simulator_name: 'hrl'

rl:
  mode: test    # Select from: train, continual_train, test, debug (check_env many times for the baseline).

  train:
    total_timesteps: 100000000
    checkpoints_folder_name: 0813_hrl_supervisory_control_100m_agent_b_uncertain_events_uncertain_agents
    num_workers: 10   # Smaller than the laptop's number of processes: 16 - should not be the maximum capacity of the processors, otherwise the local memory will overflow.
    num_steps: 5000   # Don't change this parameter
    batch_size: 500   # We recommend using a `batch_size` that is a factor of `n_steps * n_envs`
    ent_coef: 0.03    # Entropy coefficient
    n_epochs: 10       # Number of epochs
    clip_range: 0.2   # Clipping range
    clip_range_vf: None   # Clipping range for the value function
    learning_rate:   # Learning rate
      initial_value: 1e-5
      min_value: 1e-7
      threshold: 0.8
    device: 'cuda'     # 'cuda' for default
    save_freq: 5000000  # Save a checkpoint every 0.5 million steps

  test:
    num_episodes: 1
    loaded_model_name: 'rl_model_35000000_steps'
    continual_logs_name: 'PPO_201'

    grid_search_perturbation:
      enable: False
      dwell_steps: [[0.2, 0.5], 0.01]
      amp_tuning_factor: [[0, 1], 0.01]
      perturbation_amp_noise_scale: [[0, 0.015], 0.001]
    grid_search_selection:
      enable: False
      init_delta_t: [[1, 5], 0.5]
      init_sigma_position_memory: [[0.5, 10], 0.5]
      weight_memory_decay: [[0.1, 1], 0.1]
      spatial_dist_coeff: [[2, 10], 0.5]
      layouts: ['L0', 'L50', 'L100']
      num_episodes: 50
    grid_search_supervisory_control:
      enable: True
      agent_name: 'agent_b'   # 'agent a' or 'agent b' or 'agent c'
      layouts: ['L0', 'L50', 'L100']
      event_update_levels: ['short', 'middle', 'long']
      num_episodes: 100
