simulator_name: 'moving_eye'

rl:
  mode: debug    # Select from: train, continual_train, test, debug (check_env many times for the baseline), and interact.

  train:
    total_timesteps: 40000000
    checkpoints_folder_name: 'checkpoints_0421_rlocstkfrm_40m'
    num_workers: 12   # Smaller than the laptop's number of processes: 16 - should not be the maximum capacity of the processors, otherwise the local memory will overflow.
    num_steps: 4096   # TODO do not change this parameter
    batch_size: 512   # We recommend using a `batch_size` that is a factor of `n_steps * n_envs`
    ent_coef: 0.03    # Entropy coefficient
    n_epochs: 10       # Number of epochs
    clip_range: 0.2   # Clipping range
    clip_range_vf: None   # Clipping range for the value function
    learning_rate: 0.0001   # Learning rate
    device: 'cuda'     # 'cuda' for default
    save_freq: 50000  # Save a checkpoint every 0.5 million steps

  test:
    num_episodes: 1
    layout_name: 'interline-spacing-100'    # Choose from 'interline-spacing-100', 'bottom-center', 'middle-right'
    loaded_model_name: 'rl_model_2800000_steps'
    continual_logs_name: 'PPO_88'

mj_env:
  xml: 'locomotion-12-3layouts-v1.xml'
  width: 80
  height: 80
